options:
  volume-dd-blocksize:
    description: Block size volume should use
    default: 512
    type: int
  nas-login:
    description: username for accessing array
    default: root
    type: string
  nas-password:
    description: password for accessing array
    default: password
    type: string
  nas-server-hostname:
    description: hostname of array
    default: 10.5.90.13
    type: string
  nas-volume-backend-name:
    description: Backend volume name to use in cinder
    default: iXsystems_FREENAS_Storage
    type: string
  nas-iqn-prefix:
    description: IQN prefix for accessing pool
    default: iqn.2005-10.org.freenas.ctl
    type: string
  nas-datastore-pool:
    description: Datastore pool name to use from within array
    default: vol1
    type: string
  nas-vendor-name:
    description: Vendor name
    default: iXsystems
    type: string
  nas-storage-protocol:
    description: Protocol to use when attaching volume (usually iscsi or NFS)
    default: iscsi
    type: string
  driver-source:
    type: string
    default: ppa:gnuoy/cinder-xenial-ocata
    description: |
      Optional configuration to support use of additional sources such as:
        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main
      The last option should be used in conjunction with the key configuration
      option.
  driver-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
